In [53]:
from sklearn.linear_model import LinearRegression
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import mean_squared_error, mean_absolute_error, mean_absolute_percentage_error,r2_score
from sklearn.model_selection import train_test_split

In [54]:
syntax: mean_squared_error(yactual,ypredicated)

NameError: name 'yactual' is not defined

In [6]:
df=pd.read_csv("Salary_Data.csv")
df

Age  Gender    Education Level              Job Title  \
0     32.0    Male         Bachelor's      Software Engineer   
1     28.0  Female           Master's           Data Analyst   
2     45.0    Male                PhD         Senior Manager   
3     36.0  Female         Bachelor's        Sales Associate   
4     52.0    Male           Master's               Director   
...    ...     ...                ...                    ...   
6699  49.0  Female                PhD  Director of Marketing   
6700  32.0    Male        High School        Sales Associate   
6701  30.0  Female  Bachelor's Degree      Financial Manager   
6702  46.0    Male    Master's Degree      Marketing Manager   
6703  26.0  Female        High School        Sales Executive   

      Years of Experience    Salary  
0                     5.0   90000.0  
1                     3.0   65000.0  
2                    15.0  150000.0  
3                     7.0   60000.0  
4                    20.0  200000.0  
...                   ...       ...  
6699                 20.0  200000.0  
6700                  3.0   50000.0  
6701                  4.0   55000.0  
6702                 14.0  140000.0  
6703                  1.0   35000.0  

[6704 rows x 6 columns]

In [7]:
df.head()

Age  Gender Education Level          Job Title  Years of Experience  \
0  32.0    Male      Bachelor's  Software Engineer                  5.0   
1  28.0  Female        Master's       Data Analyst                  3.0   
2  45.0    Male             PhD     Senior Manager                 15.0   
3  36.0  Female      Bachelor's    Sales Associate                  7.0   
4  52.0    Male        Master's           Director                 20.0   

     Salary  
0   90000.0  
1   65000.0  
2  150000.0  
3   60000.0  
4  200000.0

In [15]:
x=df[['Age']]
x.head()

Age
0  32.0
1  28.0
2  45.0
3  36.0
4  52.0

In [16]:
y=df.Salary
y

0        90000.0
1        65000.0
2       150000.0
3        60000.0
4       200000.0
          ...   
6699    200000.0
6700     50000.0
6701     55000.0
6702    140000.0
6703     35000.0
Name: Salary, Length: 6698, dtype: float64

In [13]:
df.isnull().sum()                                         # to check if the nulll value exist or not 
df.dropna(inplace=True)

In [18]:
linearmodel =LinearRegression()                          # linear regression vanne class ko obj banayako that is linearmodel
linearmodel.fit(x,y) 

LinearRegression()

In [20]:
linearmodel.intercept_


np.float64(-54354.247682993664)

In [21]:
linearmodel.coef_

array([5046.64636526])

In [23]:
linearmodel.predict([[45]])

C:\Users\Acer\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([172744.83875362])

# Mean Square Error

In [25]:
ypred = linearmodel.predict(x)


In [ ]:
x     -y  ypred

In [26]:
x.head()

Age
0  32.0
1  28.0
2  45.0
3  36.0
4  52.0

In [27]:
y

0        90000.0
1        65000.0
2       150000.0
3        60000.0
4       200000.0
          ...   
6699    200000.0
6700     50000.0
6701     55000.0
6702    140000.0
6703     35000.0
Name: Salary, Length: 6698, dtype: float64

In [28]:
ypred

array([107138.43600527,  86951.85054423, 172744.83875362, ...,
        97045.14327475, 177791.48511888,  76858.55781372], shape=(6698,))

In [29]:
error=y-ypred

In [30]:
error

0      -17138.436005
1      -21951.850544
2      -22744.838754
3      -67325.021466
4       -8071.363310
            ...     
6699     7068.575785
6700   -57138.436005
6701   -42045.143275
6702   -37791.485119
6703   -41858.557814
Name: Salary, Length: 6698, dtype: float64

In [34]:
error2=np.power(error,2)
error2

0       2.937260e+08
1       4.818837e+08
2       5.173277e+08
3       4.532659e+09
4       6.514691e+07
            ...     
6699    4.996476e+07
6700    3.264801e+09
6701    1.767794e+09
6702    1.428196e+09
6703    1.752139e+09
Name: Salary, Length: 6698, dtype: float64

In [37]:
# mean Squared Error 
mse=np.mean(error2)
print(f"MSE:{mse:.2f}")

MSE:1309381284.73


or it can be done as mathi ko mse nikalne arko tarika ho yo 
mse=np.mean(np.power(error,2))

In [39]:
mse=mean_squared_error(y,ypred)
print(f"MSE:{mse:.2f}")

MSE:1309381284.73


In [40]:
# Root Mean Square Error 
rmse=np.sqrt(mse)
print(f"RMSE:{rmse:.2f}")

RMSE:36185.37


In [42]:
# Mean absloute Error
mae = mean_absolute_error(y, ypred)
print(f"MAE:{mae:.2f}")


MAE:28908.93


In [45]:
# mean Absolute Percentage Error
mape = mean_absolute_percentage_error(y, ypred)
mape=mape*100
print(f"MAPE:{mape:.2f}%")

MAPE:45.94%


In [51]:
# R2 Square
r2 = r2_score(y, ypred) 
print(f"R2_score: {r2:.2f}")

R2_score: 0.53


In [ ]:
Train
x=> predection               ypred 

testing 
=> while testing dont give the data of training 
=> training ma deyako data testing ma use graidina 

In [ ]:
So, Data is divided into two parts 
1. one is training(dherai data chai training ma pass garinxa (80%)) and 
=>x _train, y_train
2. one is testing(20%) 
=>x_test,y_test

In [ ]:
Data
first ma (x,y) theyo
xtrain, xtest                       ytrain, ytest

In [52]:
from sklearn.model_selection import train_test_split


In [55]:
data=pd.read_csv("Salary_Data.csv")
data

Age  Gender    Education Level              Job Title  \
0     32.0    Male         Bachelor's      Software Engineer   
1     28.0  Female           Master's           Data Analyst   
2     45.0    Male                PhD         Senior Manager   
3     36.0  Female         Bachelor's        Sales Associate   
4     52.0    Male           Master's               Director   
...    ...     ...                ...                    ...   
6699  49.0  Female                PhD  Director of Marketing   
6700  32.0    Male        High School        Sales Associate   
6701  30.0  Female  Bachelor's Degree      Financial Manager   
6702  46.0    Male    Master's Degree      Marketing Manager   
6703  26.0  Female        High School        Sales Executive   

      Years of Experience    Salary  
0                     5.0   90000.0  
1                     3.0   65000.0  
2                    15.0  150000.0  
3                     7.0   60000.0  
4                    20.0  200000.0  
...                   ...       ...  
6699                 20.0  200000.0  
6700                  3.0   50000.0  
6701                  4.0   55000.0  
6702                 14.0  140000.0  
6703                  1.0   35000.0  

[6704 rows x 6 columns]

In [56]:
data.head()

Age  Gender Education Level          Job Title  Years of Experience  \
0  32.0    Male      Bachelor's  Software Engineer                  5.0   
1  28.0  Female        Master's       Data Analyst                  3.0   
2  45.0    Male             PhD     Senior Manager                 15.0   
3  36.0  Female      Bachelor's    Sales Associate                  7.0   
4  52.0    Male        Master's           Director                 20.0   

     Salary  
0   90000.0  
1   65000.0  
2  150000.0  
3   60000.0  
4  200000.0

In [57]:
data.isnull().sum()

Age                    2
Gender                 2
Education Level        3
Job Title              2
Years of Experience    3
Salary                 5
dtype: int64

In [58]:
data.dropna(inplace=True)

In [59]:
data.isnull().sum()

Age                    0
Gender                 0
Education Level        0
Job Title              0
Years of Experience    0
Salary                 0
dtype: int64

In [60]:
x=data[['Age']]
y=data.Salary

In [71]:
# split to train and train
# random_state= same split rahairahanxa matlab harayak time train rw test value split huda fix hudaina yesle chai fix garna help garxa
#7 matrw rakhno parxa vannae hudaina  j rakhna ni payainxa tera jaba samma 7 lai change garidana teti bela samma train test value change hudaian
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=7)

In [72]:
xtrain

Age
2929  46.0
4258  27.0
374   44.0
1132  34.0
1779  48.0
...    ...
5704  26.0
2553  31.0
539   27.0
1222  42.0
4275  29.0

[5358 rows x 1 columns]

In [73]:
ytrain

2929    150729.0
4258     36000.0
374     150000.0
1132    195000.0
1779    185000.0
          ...   
5704     55000.0
2553    100052.0
539     140000.0
1222    180000.0
4275     71000.0
Name: Salary, Length: 5358, dtype: float64

In [74]:
model=LinearRegression()
model.fit(xtrain,ytrain)

LinearRegression()

In [ ]:
# aba evaluation garna ko lagi hami xtest rw ytest dinxau for the predection(ypred)

In [75]:
ypredection=model.predict(xtest)

In [76]:
ypredection

array([ 96864.3975814 ,  91857.04807984, 136923.19359391, ...,
        76834.99957515,  96864.3975814 , 106879.09658453], shape=(1340,))

In [ ]:
xtest      ytest  ypredection

In [78]:
mae = mean_absolute_error(ytest, ypredection)
print(f"MAE:{mae:.2f}")

MAE:28870.10


# Assignment x=Age, Years of experience 

In [ ]:
x=data[['Age','Years of experiece']]