<a href="https://colab.research.google.com/github/AbishekMishra183/data-science-ml-journey/blob/main/DataScience_day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Attributes
. shape
.size
.ndim
.dtype

In [ ]:
import numpy as np
x=np.array([5,7,8,2,9,15])
print(x)

[ 5  7  8  2  9 15]


In [ ]:
# shape=>  no of row and column dinxa
print(x.shape)

(6,)


In [ ]:
mat=np.array([[5,4,3],[9,7,6]])
print(mat)

[[5 4 3]
 [9 7 6]]


In [ ]:
print(mat.shape)# this is 2 d so the value of the row and colum is given

(2, 3)


In [ ]:
# size=> gives the total size of the array from the given list
print(x.shape)

(6,)


In [ ]:
# 2 d => total size of the array of the 2_d matrix
mat=np.array([[5,4,3],[9,7,6]])
print(mat.size)

6


In [ ]:
print(x.ndim)# we have created only 1 d array so output =>1

1


In [ ]:
print(mat.ndim)# this is 2 d array so output =>2

2


In [ ]:
print(x.dtype)

int64


In [ ]:
#int64
# assume to store 5  it uses the binary 64 bit to store that binary value of the 5


In [ ]:
matrix=np.array([[5,4,3],[9,7,6],[2,3,3],[2,54,5]])
print(matrix.size)

12


##Sclicing/Indexing

In [ ]:
# indexing=> to access the particular element of an array  have both the positive and the negative indexing
x=np.array([1,2,3,5])
print(x)

[1 2 3 5]


In [ ]:
print(x[1])

2


In [ ]:
print(x[-1])# this is negative indexing

5


In [ ]:
# slicing
x=np.array([1,2,3,5,6,7,8,])# syntax:x[startindex:stopindex] here stop index is exclusive  so that last element is not included
print(x[0:2])

[1 2]


In [ ]:
print(x[1:5])

[2 3 5 6]


In [ ]:
print(x[1:])# by default stop index is the last of the list

[2 3 5 6 7 8]


In [ ]:
print(x[0:3])

[1 2 3]


In [ ]:
# syntax: x[startindex:stopindex:step]# by default step is 1

In [ ]:
x=np.array([1,2,3,5,6,7,8,])
print(x[:5:2])# by default start from 1

[1 3 6]


In [ ]:
x[::]# all the array is return by default

array([1, 2, 3, 5, 6, 7, 8])

In [ ]:
print(x[::-1])# here -1 keep track the list from the backward

[8 7 6 5 3 2 1]


In [ ]:
x[1:-1]# start is 1 and the stop is -1 which is 15 so not included

array([2, 3, 5, 6, 7])

In [ ]:
x[-2:1:-1]

array([7, 6, 5, 3])

In [ ]:
x[-2:1]# why??

array([], dtype=int64)

In [ ]:
# modification in the list
print(x)

[1 2 3 5 6 7 8]


In [ ]:
x[3]=12# modifying the index 3 as 12
print(x)

[ 1  2  3 12  6  7  8]


In [ ]:
#copy
y=x[0:3]
print(y)

[1 2 3]


In [ ]:
y[0]=15# modifying the index
print(y)

[15  2  3]


In [ ]:
print(x)

[15  2  3 12  6  7  8]


In [ ]:
#copy
#view
# if we want the independent so we need to do we use.copy

In [ ]:
x=np.array([5,7,8,2,9,15])
y=x[0:3].copy()# if we copy it will create a new array sot that change is not reflected in the orginal array
print(y)

[5 7 8]


In [ ]:
y[0]=15# without use of the copy orginal array is reflected as change
print(y)

[15  7  8]


In [ ]:
print(x)

[ 5  7  8  2  9 15]


In [ ]:
# Functions:
np.sum()
np.prod()
np.min()
np.max()
np.mean()
np.std()
np.median()
np.sort()
np.unique()


TypeError: sum() missing 1 required positional argument: 'a'

In [ ]:
x=np.array([5,7,8,2,9,15])

In [ ]:
sum=np.sum(x)
print(sum)

In [ ]:
prod=np.prod(x)
min=np.min(x)
max=np.max(x)
mean=np.mean(x)
std=np.std(x)
median=np.median(x)
sort=np.sort(x)
unique=np.unique(x)
print(f"{mean:.2f}")# two deciaml places ko lagi
print(prod)
print(min)
print(max)
print(std)
print(median)
print(sort)# by default  ascending order
print(unique)

In [ ]:

# here in the case of this first sorting in ascending then reverse order is print => descending

#  Sort in descending order
sorted_desc = np.sort(x)[::-1]
print( sorted_desc)

#  Reverse the original array (does not sort, just flips)
reversed_arr = x[::-1]
print( reversed_arr)


In [ ]:
help(np.sort)

# Array Arithmetic
np.add()
np.multiply()
np.divide()
np.floor_divide()
np.mod()
np.power()
np.sqrt()

In [ ]:
x=np.array([5,4,6,1])
y=np.array([2,1,3,4])
z=np.add(x,y)
print(z)

[7 5 9 5]


In [ ]:
z=x+y
print(z)

[7 5 9 5]


In [ ]:
z=np.multiply(x,y)
print(z)

[10  4 18  4]


In [ ]:
z=x/y
print(z)

[2.5  4.   2.   0.25]


In [ ]:
z=np.floor_divide(x,y)
print(z)

[2 4 2 0]


In [ ]:
z=np.mod(x,y)
print(z)

[1 0 0 1]


In [ ]:
z=np.power(x,y)
print(z)

[ 25   4 216   1]


In [ ]:
z=np.sqrt(x)
print(z)

[2.23606798 2.         2.44948974 1.        ]


In [ ]:
z=np.add(x,2)
print(z)

[7 6 8 3]


# Assignement to do

Broadcasting
np.zeros()
np.ones()
np.full()
np.arange()
np.linspace()
np.random.random()
np.random.randint()
np.random.uniform()
