In [1]:
# day2 Datascience 

# single dimension => consider as vector but the 2 _D is the matrix representation
import numpy as np 
x=np.array([5,4,6,1])
y=np.array([2,1,3,4])
z=x+2
print(z)


[7 6 8 3]


In [ ]:
# Broadcasting while adding 2 looks like in the array x  
[5,4,6,1]+[2,2,2,2]

In [2]:
# Reshaping 
print (x.shape)

(4,)


In [3]:
x.reshape(2,2)# this is used for the reshaping the matrix 

array([[5, 4],
       [6, 1]])

In [4]:
a=np.array([4,6,2,7,9,12])
print(a.shape)

(6,)


In [5]:
a.reshape(3,2)

array([[ 4,  6],
       [ 2,  7],
       [ 9, 12]])

In [7]:
a.reshape(2,3)

array([[ 4,  6,  2],
       [ 7,  9, 12]])

In [6]:
a.reshape(1,6)# row matrix 

array([[ 4,  6,  2,  7,  9, 12]])

In [8]:
a.reshape(6,1)

array([[ 4],
       [ 6],
       [ 2],
       [ 7],
       [ 9],
       [12]])

In [9]:
print(a.reshape(6,1))# column  matrix 

[[ 4]
 [ 6]
 [ 2]
 [ 7]
 [ 9]
 [12]]


In [10]:
x=np.zeros(5)# this is a single dimensional array
print(x)

[0. 0. 0. 0. 0.]


we donot use the parnethesis in the attribute but use parenthesis in the function 

In [14]:
import numpy as np

x = np.array([5, 4, 6, 1])
y = np.array([2, 1, 3, 4])# to find the value of x with the help of y 

xpower = np.power(x, y)
print(xpower)


[ 25   4 216   1]


In [15]:
x=np.array([5,6,2,7])
add=np.insert(x, 3, 12)
print(add)

[ 5  6  2 12  7]


# there are two function to add the elements in the numpy array
first 1 is x=np.append(x,9)=> automatically insert in the last index here 9 is inserted at the last position 
z= np.insert(x,index,value)=> inserting element in the particular position or the index 

In [16]:
# np.zeros 
x=np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [18]:
x=np.zeros((2,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [20]:
x=np.zeros(10).reshape(2,5)
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [21]:
x=np.ones(5)
print(x)



[1. 1. 1. 1. 1.]


In [22]:
# np.full
z=np.full(7,5)# elements is 5 and the shape is 7  so the given vector is as in the output
print(z)


[5 5 5 5 5 5 5]


In [23]:
z=np.full((2,3),7)
print(z)

[[7 7 7]
 [7 7 7]]


In [24]:
# np.arange
#np.Linspace:::synatax:np.linspace(start,stop,how many numbers in between the range of start and stop)

x=np.arange(2,10,2)# syntax:np.arange(start,stop,step)
print(x)

[2 4 6 8]


In [25]:
# np.arange
#np.Linspace::
x=np.arange(2,10,2).reshape(2,2)
print(x)

[[2 4]
 [6 8]]


In [27]:
x=np.linspace(1,10,15)
print(x)

[ 1.          1.64285714  2.28571429  2.92857143  3.57142857  4.21428571
  4.85714286  5.5         6.14285714  6.78571429  7.42857143  8.07142857
  8.71428571  9.35714286 10.        ]


np.random.random()
np.random.randint()
np.random.uniform()

In [39]:
x=np.random.random(5000)   # generates random numbers between 0  to -1 
print(x[4000:5000])

[0.74746424 0.95251484 0.91091179 0.86256905 0.07293037 0.60533394
 0.91909478 0.9799052  0.06711372 0.24800064 0.72621992 0.18971481
 0.41361811 0.49212886 0.66134592 0.55547955 0.07676465 0.79285583
 0.32091847 0.6734437  0.68115664 0.59325917 0.36164354 0.942773
 0.93991684 0.01665427 0.79217161 0.05048964 0.05929205 0.93488077
 0.56141231 0.13879319 0.85684741 0.16443549 0.79893311 0.13934849
 0.90532161 0.15632636 0.97830092 0.0287464  0.41635884 0.19858548
 0.60064198 0.80659393 0.63748876 0.35893383 0.67751649 0.99511246
 0.18618195 0.12157133 0.03606427 0.7622934  0.6048987  0.11641527
 0.40565517 0.85588163 0.78458331 0.25084456 0.74690381 0.12294722
 0.70154769 0.87593567 0.49291992 0.77883086 0.28996902 0.87219989
 0.43857974 0.65996161 0.02815332 0.03948974 0.62508097 0.37562236
 0.42128039 0.1814754  0.67244155 0.16395393 0.93326599 0.84402879
 0.72716471 0.48102005 0.48977023 0.34271846 0.12583264 0.55432019
 0.81087883 0.16762054 0.92831802 0.6266535  0.64975431 0.766676

In [31]:
x=np.random.random((5,2))
print(x)

[[0.32110841 0.55809553]
 [0.30916471 0.23462515]
 [0.80887277 0.48381362]
 [0.06102631 0.48499975]
 [0.04292558 0.44404784]]


In [34]:
y=np.random.randint(0,10,5) # generates 5 number from 0 to 10 randomly 
print(y)

[8 0 1 7 7]


In [35]:
y=np.random.randint(0,10,15) # generates 15 number from 0 to 10 randomly 
print(y)

[4 8 9 8 4 0 4 8 7 5 5 4 3 3 0]


In [37]:
y=np.random.randint(0,10,5) # generates 5 number from 0 to 10 randomly 
print(y)

[0 3 3 9 7]


In [38]:
z=np.random.uniform(0,10,5) # uniform is used to generate the floating point number randomly 
print(z)

[6.26875419 3.038925   8.68068687 2.70384858 4.77881023]


# pandas start from here >>>>>>>>>>>>>>> stands for the python data analytics 
#tabular data lai operate garna sakinccha => operate in the row coluum data
two data structure
>series
>Dataframe 


In [40]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [42]:
import pandas as pd 


In [46]:
# Series 
x=pd.Series([5,7,9,2],index=['a','b','c','d'])# output is like in the tabular format 
print(x)

a    5
b    7
c    9
d    2
dtype: int64


In [ ]:
x=pd.Series([5,7,9,2])# output is like in the tabular format 
print(x)

In [44]:
print(x[3])

2


# Assignment
.loc()
.iloc()